export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const ADD_MODAL_IS_VISIBLE = 'ADD_MODAL_IS_VISIBLE';
export const EDIT_MODAL_IS_VISIBLE = 'EDIT_MODAL_IS_VISIBLE';


